---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: manul
# description will be included in the image's metadata
description: Image based on ublue kinoite-main.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - micro
      - starship
      - fastfetch
      - android-tools
      #- https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-%OS_VERSION%.noarch.rpm
      #- https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-%OS_VERSION%.noarch.rpm
      - steam
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system)"
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.mozilla.firefox
        - com.obsproject.Studio
      # remove:
        #- org.gnome.eog
    user:
      repo-name: flathub-user
      repo-title: "Flathub (user)"
      install:
        - com.discordapp.Discord
        - io.openrct2.OpenRCT2
        - com.bitwarden.desktop
        - org.prismlauncher.PrismLauncher
        - com.stremio.Stremio

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

