---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: manul
# description will be included in the image's metadata
description: Image based on ublue kinoite-main.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora-ostree-desktops/kinoite
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: os-release
    properties:
        ID: fedora
        NAME: RyeOS
        PRETTY_NAME: RyeOS Kinoite
        DEFAULT_HOSTNAME: manul

  - type: rpm-ostree
    repos:
       - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
       - https://copr.fedorainfracloud.org/coprs/lilay/topgrade/repo/fedora-%OS_VERSION%/lilay-topgrade-fedora-%OS_VERSION%.repo

    install:
      - micro
      - starship
      - android-tools
      - topgrade
      #- https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
      #- https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)


  - type: dnf
    repos:
        nonfree: rpmfusion
        copr:
        - bazzite-org/bazzite
        - bazzite-org/bazzite-multilib
        files:
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
        - https://copr.fedorainfracloud.org/coprs/ublue-os/packages/repo/fedora-%OS_VERSION%/ublue-os-packages-fedora-%OS_VERSION%.repo
    install:
      skip-unavailable: true
      packages:
      - steam
      - f22-backgrounds-base
      - f23-backgrounds-base
      - f24-backgrounds-base
      - qemu-kvm
      - libvirt-daemon-kvm
      - libvirt-daemon-config-network
      - virt-install
      - virt-manager
      - ublue-fastfetch

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system)"
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.mozilla.firefox
        - com.obsproject.Studio
        - org.videolan.VLC
      # remove:
        #- org.gnome.eog
    user:
      repo-title: "Flathub (user)"
      install:
        - com.discordapp.Discord
        - io.openrct2.OpenRCT2
        - com.bitwarden.desktop
        - org.prismlauncher.PrismLauncher
        - com.stremio.Stremio
        - com.rawtherapee.RawTherapee
        - com.heroicgameslauncher.hgl
        - com.github.tchx84.Flatseal

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

